{% set version = "2.6" %}

package:
  name: jplephem
  version: {{ version }}

source:
  fn: jplephem-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jplephem/jplephem-{{ version }}.tar.gz
  md5: 5959775cba483a88dd879a74e0b52971
  patches:
    - 0001_use-setuptools.patch

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

test:
  imports:
    - jplephem

about:
  home: https://pypi.python.org/pypi/jplephem
  license: MIT
  summary: "Python version of NASA DE4xx ephemerides, the basis for the Astronomical Alamanac"

extra:
  recipe-maintainers:
    - juanlu001
    - brandon-rhodes
    - jochym
