{% set name = "jplephem" %}
{% set version = "2.6" %}
{% set sha256 = "b1be79d85d7a2fa06a122c979ab0d30d7a0c295e8c197b05c85d16a5484b2143" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001_use-setuptools.patch

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

test:
  imports:
    - jplephem

about:
  home: https://pypi.python.org/pypi/jplephem
  license: MIT
  summary: "Python version of NASA DE4xx ephemerides, the basis for the Astronomical Alamanac"

extra:
  recipe-maintainers:
    - juanlu001
    - brandon-rhodes
    - jochym
