{% set name = "jplephem" %}
{% set version = "2.7" %}
{% set sha256 = "328d8561ee4189f259d9a807a01b3f2b5a4ff91484b79f5cf6f99cab3354c825" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001_use-setuptools.patch

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

test:
  imports:
    - jplephem

about:
  home: https://pypi.python.org/pypi/jplephem
  license: MIT
  summary: "Python version of NASA DE4xx ephemerides, the basis for the Astronomical Alamanac"

extra:
  recipe-maintainers:
    - juanlu001
    - brandon-rhodes
    - jochym
