travis:
  secure:
    BINSTAR_TOKEN: oBrp9eWR2J7FMDffx1lOlxLCotdFPELi/lryV2QsbZZ+SMuIbzDs5PsY7vPFbe5Hg2pTT7do+WlMv2i4E8Sdy/4QFqLcSwNxlFb/5+u8bBXLsLLheAdjVSOARqjhKs3mCiSFA/EaZMFJxfBWi8MaWVz2JCiY7PXUhANR3UFXv+I+XU1Wfa3GKtIuUyRrJMeSAI8YAQ0kHtyeudXSYEWizdjmjGHPu+O0gMKSGqbqkw7V4tslwtL3HtWgJsht6mtvfXuqF0hRPnk737YnoY7aS0gWcWV0lx7BrtAr5aNCTmaG8mSS4nK24YW1FMkGYNNMbzCf9U88vy335IZdDtn3/Wbpulpcj1TQl8JrfA8KRwEsv2hUqDfTLQxF9FA1oNgZj6TDMmyCg5Rx/tA/kxwBzPqkCB4ntcvAE86nT0CBXuTTZ5ttvaLSpI4GWQhxUlzwpz12OQ1ehaGgyLgOQ6nbWyfgG5SKmKNlvgzUB+OaUE1XriFT87oJVfEdI4I/EuUCusjh9SdBHPKnhQA5hej6CPTeVb0MIQ7GzgHzvywmE2APri4vbjvooynuOZrTGk1G9NdgNs28typmllP7p57dkS2hOjRkUOUP4Kq08jQNZCXS7Y3G0CYxzqHwjn86APKtu/kaOi2ORKeRAaYfioB0Ti86wqJ/W8A3y3oY8A4KOVA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
