travis:
  secure:
    BINSTAR_TOKEN: Uzl/3aN4fHy6uanj6bfuGyhigcGJ1zuKdbbDGofzcv0D1TnDFdWlnRV1D9rwvww/humhlLAEOrv21dVC+srkjrcYGvWLFN0F7B5Najii+B4Vezbx/DJlOi7qh3MissXs/sFrXZyEV9SKTWgsneH5vqKXbZgnEJRBTlJdFnQRE9HmjtLYn0IU3f/Sij2B01tZeOwVi/P0FNEwDQn7gaSU/xZ5pyFQTeB/1N474VZxXhCdaJGKMaYm9FfqRFdcX0V/SK4otT19NdxA3RDVBa0ewPu+SSjg4AQh81OajPflBauTciYKbKsmCeUeAZdYq83heFAr+5Zd31tD9YXj+sAupJ5SU3PttUaVT0rLVG7mORh9j4kfpeW1gEXjoGo71sqtNivPsE/XrgAn6tnfqiYv6mY2AjLOMupNRngxBbHcs+Uc63fx4up2uO0cMQZdQp4EL4/zPvNkGCvqmWS7lessmGv/aaDY/JMEJQHd/ciWPkGItB0syv8am4yCGGOYmM2G0HcjmVbcbD2g2DUBEPPRkcbNJV2K6NJYd/k6au97l+qBy8lZUhJK8YgwlzA6gejuoZ+UHhy8fw9W9m51G2UE6O5XqIyoqzYFYW3v5WD6l8XVEEH8uu5Gt51WRAS+QM9P8Rq0Q5ng1vXrWQa7vsUFDfEgH+Lzq3S1UyAdEgCuWbo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
