travis:
  secure:
    BINSTAR_TOKEN: T9z5HIaZQWe9+yQsnh8oI4MMAT6A3K2iZ/YDtDuXs4TAmb9L6s6OshfW/tqvmsh8mdOx2ab87ifGtE6/kGS91XqmhvUVoZLhZk1xMOSKmkSH+GR41GGAqiJyzfhe26tHi49WgWb8Zql5sMFHN2OV0Ria9ygGyy7G4BUldjVt4uUnKK+X3N5yzPFJ/VbTrQsc3gdJfV5Tv4t5lXiI61qsV6KXRuf5ostt5ZCTSWNP0Ad0GbveTXGea7z9dNnbva4GCSUZVnkS+vjxc2kuYt3sYKoUCVXEUcQqZ/OYv1YpbuD66/i0bG4h83yHbc+rt2/CsxrK+bNXbn5l5nCdRxb5f0K1/dgEeINx/2PA2xnP/sxjvvIhAvdcM1MlEGiTEnjGhbMi/jlYTEXDo1XEEoVglT2HhJbB/Fu7JDDjUfRE7PO7BkDMmiBX9omfqusiogMeA39gYGxTEsj+jnVTRaRfAO354Qbh5tcGBwJTLaedMqBaPt0xUYLI238pbQycY1h/GqZIkKteZmgbNngCxW6B8zmUbtEmdHBff9KWaBRHYfKANe6CCkFnpNkH+GkO/W+hPScq0jPsOgIP5mi9e9iPcCV62FaPEufeOC2/KiO3Z2mbMrq2nhDlXWd+pVYQaQDJE3Mq/18MPqL2UxV/8wcPOl2sH2dljjOpmhHN9sFeaAY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
